name = "(F.B.P.) Future Battlefield Pack: Infantry Warfare"
uid = "5t3edt-btz6-9438-h6ui-967gt56fa9"
version = 1.0
copyright = "Copyright © 2020, CDRMV (aka CDR Deadalus)"
description = "'Future Battlefield Pack: Infantry Warfare' is a Submod for F.B.P: Legends, which adds Infantry Classes into the Game."
author = "CDRMV (aka CDR Deadalus)"
url = "http://www.moddb.com/mods/fbp-future-battlefield-pack"
icon = "/mods/Future Battlefield Pack Infantry Warfare/Icon.png" 
selectable = true
enabled = true
exclusive = false
ui_only = false
requires = { }
requiresNames = { }
conflicts = { }
before = { }
after = { }
